import type { Metadata } from "next";
import "./globals.css";
import { SITE_QUERY } from "@/sanity/lib/queries";
import { client } from "@/sanity/lib/client";
import { SiteSettings } from "@/sanity/types";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteSettings = await client.fetch(SITE_QUERY);
  const favicon = siteSettings?.favicon?.asset?.url;
  console.log('favicon', favicon);
  // debugger;
  return (
    <html lang="en">
      {/* favicon from site Settings */}
      {favicon && <link rel="icon" href={favicon} />}
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
